export const logo = require("./images/Splash/logo.png");
export const google = require("./images/Login/google.png");
export const Apple = require("./images/Login/Apple.png");
export const WhiteOutLoginUser = require("./images/Drowe/WhiteOutLoginUser.png");
export const edit = require("./images/Drowe/edit.png");
export const insta = require("./images/Drowe/insta.png");
export const fbimg = require("./images/Drowe/fbimg.png");
export const chatapp = require("./images/Drowe/chatapp.png");
export const firstBanner = require("./images/Home/phone1.jpg");
export const banner2 = require("./images/Home/banner2.png");
export const NewIcon = require("./images/Home/NewIcon.png");
export const doneIcon = require("./images/Payment/done.png");
export const ErrorIcon = require("./images/Payment/ErrorIcon.png");
export const Shippment = require("./images/Payment/Shippment.png");
export const Ratting = require("./images/Payment/Ratting.png");
export const WomenBanner = require("./images/Home/WomenBanner.png")
export const WC1 = require("./images/Home/WC1.png")
export const Sider1 = require("./images/Home/Sider1.png")
export const MensBanner = require("./images/Home/MensBanner.jpg")
export const ShopBug = require("./images/Common/ShoppingBag.jpg")
export const  bannecrSC= require("./images/Common/bannecrSC.png")
export const  SoupanserIcon= require("./images/Common/SoupanserIcon.png")
export const  A= require("./images/Common/A.png")
export const  whatsapp= require("./images/Common/whatsapp.png")
export const  bussnis1= require("./images/Common/bussnis1.png")
export const  VAT= require("./images/Common/VAT.png")
export const  Giftcard= require("./images/Common/giftcard.jpg")

// export const  ErrorImg = require("./images/Payment/ErrorImg.png")