export const FONTS = {
    Black: "Roboto-Black",
    BlackItalic: "Roboto-BlackItalic",
    Bold: "Roboto-Bold",
    BoldItalic: "Roboto-BoldItalic",
    ExtraBold: "Roboto-ExtraBold",
    ExtraBoldItalic: "Roboto-ExtraBoldItalic",
    ExtraLight: "Roboto-ExtraLight",
    ExtraLightItalic: "Roboto-ExtraLightItalic",
    Italic: "Roboto-Italic",
    Light: "Roboto-Light",
    LightItalic: "Roboto-LightItalic",
    Medium: "Roboto-Medium",
    MediumItalic: "Roboto-MediumItalic",
    Regular: "Roboto-Regular",
    SemiBold: "Roboto-SemiBold",
    SemiBoldItalic: "Roboto-SemiBoldItalic",
    Thin: "Roboto-Thin",
    ThinItalic: "Roboto-ThinItalic",
}