export const FONTS = {
    RalewayBlack: "Raleway-Black",
    RalewayBlackItalic: "Raleway-BlackItalic",
    RalewayBold: "Raleway-Bold",
    RalewayExtraBold: "Raleway-ExtraBold",
    RalewayExtraBoldItalic: "Raleway-ExtraBoldItalic",
    RalewayExtraLight: "Raleway-ExtraLight",
    RalewayExtraLightItalic: "Raleway-ExtraLightItalic",
    RalewayItalic: "Raleway-Italic",
    RalewayLight: "Raleway-Light",
    RalewayLightItalic: "Raleway-LightItalic",
    RalewayMedium: "Raleway-Medium",
    RalewayMediumItalic: "Raleway-MediumItalic",
    RalewayRegular: "Raleway-Regular",
    RalewaySemiBold: "Raleway-SemiBold",
    RalewaySemiBoldItalic: "Raleway-SemiBoldItalic",
    RalewayThin: "Raleway-Thin",
    RalewayThinItalic: "Raleway-ThinItalic",
}