export const Ar = {
  hello: 'مرحبًا',
  Home: 'بيت',
  Category: 'فئة',
  Notification: 'إشعار',
  Profile: 'حساب تعريفي',
  CUSTOMERSERVICE: 'خدمة الزبائن',
  LOGOUT: 'تسجيل خروج',
  TopCategories: 'أهم الفئات',
  FEATUREPRODUCTS: 'المنتجات المميزة',
  SPECIALPRODUCTS: 'المنتجات الخاصة',
  LATESTPRODUCTS: 'أحدث المنتجات',
  GAMES: 'ألعاب',
  SCHOOL: 'مدرسة',
  LOGIN: 'تسجيل الدخول',
  ViewAll: 'عرض الكل',
  Wishlist: 'قائمة الرغبات',
  MyWallet: 'محفظتى',
  AddressBook: 'دليل العناوين',
  MyOrder: ' طلب',
  CustomerService: 'خدمة الزبائن',
  phone: 'هاتف',
  Email: 'البريد الإلكتروني',
  Password: 'كلمة المرور',
  Rememberme: 'تذكرنى',
  ForgotPassword: 'هل نسيت كلمة السر',
  SignIn: 'تسجيل الدخول',
  NewCustomer: 'عميل جديد',
  SignUp: 'اشتراك',
  SignInWithEmail: 'تسجيل الدخول باستخدام البريد الإلكتروني',
  UseMobileNo: 'استخدم رقم الجوال',
  SendOTP: 'أرسل كلمة مرور لمرة واحدة',
  CreateyourAccount: ' أنشئ حسابك',
  firstname: 'الاسم الأول',
  lastname: ' اسم العائلة',
  confirmpassword: 'تأكيد كلمة المرور',
  MoblieNo: 'رقم المحمول',
  Submit: 'يُقدِّم',
  ChangeLang : 'English',
  Enteryouremail : 'أدخل بريدك الإلكتروني',
  Enteryourpassword : 'ادخل رقمك السري',
  Entermobilenumber: 'أدخل رقم الجوال',
  EnteryourFirstname : 'أدخل اسمك الأول',
  Enteryourlastname : 'أدخل اسمك الأخير',
  OPTVerification:"التحقق من الأراضي الفلسطينية المحتلة",
  Verificationhasbeensendto : "تم إرسال التحقق إلى",
  Resend:"إعادة إرسال",
  Enteremailaddress:"أدخل عنوان البريد الالكتروني",
  Invalidemailaddress:"عنوان البريد الإلكتروني غير صالح",
  Enterpassword : "أدخل كلمة المرور",
  Invalidpassword:"رمز مرور خاطئ",
  Enterfirstname:  " أدخل الاسم الأول",
  Enterlastname:"إدخال اسم آخر",
  Invalidnumber:"رقم غير صالح",
  Numbercontainsmustbe9digits:"يجب أن يحتوي الرقم على 9 أرقام",
  Passwordandconfirmpasswordmismatch:"كلمة المرور وتأكيد كلمة المرور غير متطابقين",
  EXPassword:"على سبيل المثال: Abc@1234",
  Sponser:"راعي",
  manageWallate : "إدارة المحفظة",
  addCustomer: "إضافة العميل",
  addCustomerToGroup: "إضافة عميل إلى المجموعة",
  tranferAmount : "مبلغ التحويل",
  CreateAccount: "إنشاء حساب",
  NickName: "كنية",
  ConfirmEmailAddress:"أكد عنوانك الإلكتروني",
  SelectCustomertoaddwalletbalance: "حدد العميل لإضافة رصيد المحفظة",
  Selectcustomer:"حدد العميل",
  AmountSAR : "المبلغ (ريال سعودي)" ,
  addyourremark : "أضف ملاحظتك",
  Addmoneytocustomerswallet: "إضافة الأموال إلى محفظة العميل",
  Send : "يرسل",
  forgetDes:"الرجاء إدخال عنوان بريدك الإلكتروني وسنرسل لك \n كلمة المرور عبر البريد الإلكتروني \n فورًا",
  EditProfile : "تعديل الملف الشخصي",
  ChangePassword : "تغيير كلمة المرور",
  Update : "اخلع",
  EnterYourOldPassword: "أدخل كلمة المرور القديمة الخاصة بك"
}

export const En = {
  
  hello: 'Hello',
  Home: 'Home',
  Category: 'Category',
  Notification: 'Notification',
  Profile: 'Profile',
  CUSTOMERSERVICE: 'CUSTOMER SERVICE',
  LOGOUT: 'LOGOUT',
  TopCategories: 'Top Categories',
  FEATUREPRODUCTS: 'Feature Products',
  SPECIALPRODUCTS: 'Special Products',
  LATESTPRODUCTS: 'Latest Products',
  GAMES: 'Games',
  SCHOOL: 'School',
  LOGIN: 'LOGIN',
  ViewAll: 'View All',
  Wishlist: 'Wishlist',
  MyWallet: 'My Wallet',
  MyOrder: 'My Order',
  AddressBook: 'Address Book',
  CustomerService: 'Customer Service',
  Email: 'E-mail',
  phone: 'phone',
  Password: 'Password',
  Rememberme: 'Remember me',
  ForgotPassword: 'Forgot Password',
  SignIn: 'Sign In',
  NewCustomer: 'New Customer',
  SignUp: 'Sign Up',
  SignInWithEmail: 'Sign In With Email',
  UseMobileNo: 'Use Mobile No',
  SendOTP: 'Send OTP',
  CreateyourAccount: 'Create your Account',
  firstname: 'first name',
  lastname: 'last name',
  confirmpassword: 'confirm-password',
  MoblieNo: 'Moblie No',
  Submit: 'Submit',
  ChangeLang:'عربي',
  Enteryouremail :"Enter your email",
  Enteryourpassword : "Enter your password",
  Entermobilenumber : "Enter mobile number",
  EnteryourFirstname : "Enter your Firstname",
  Enteryourlastname:"Enter your last name",
  OPTVerification:"OPT Verification",
  Verificationhasbeensendto : "Verification has been send to",
  Resend:"Resend",
  Enteremailaddress : "Enter email address",
  Invalidemailaddress : "Invalid Email Address",
  Enterpassword:"Enter password",
  Invalidpassword:"Invalid Password",
  Enterfirstname:"Enter first name",
  Enterlastname:"Enter last name",
  Invalidnumber:"Invalid Number",
  Numbercontainsmustbe9digits : "Number contains must be 9 digits",
  Passwordandconfirmpasswordmismatch: "Password and confirm-password mismatch",
  EXPassword : "EX : Abc@1234",
  Sponser : "sponsor",
  manageWallate: "Manage wallet",
  addCustomer: "Add Customer",
  addCustomerToGroup : "Add Customer To Group",
  tranferAmount: "transfer amount",
  CreateAccount : "Create Account",
  NickName : "Nick Name",
  ConfirmEmailAddress : "Confirm Email Address",
  SelectCustomertoaddwalletbalance : "Select Customer to add wallet balance",
  Selectcustomer : "Select customer",
  AmountSAR:"Amount (SAR)",
  addyourremark : "add your remark",
  Addmoneytocustomerswallet : "Add money to customer's wallet",
  Send : "Send",
  forgetDes : "Please enter your email address and we \n  will send you password by email \n immadiatly",
  EditProfile : "Edit Profile",
  ChangePassword : "Change Password",
  Update: "Update",
  EnterYourOldPassword : "Enter Your Old Password"
  // WishList: 'WishList',
  // MyWallet: 'My Wallet',
  // MyOrder: 'My Order',
  // AddressBook: 'Address Book',
  // CustomerService: 'Customer Service'
};
